---
# tasks file for looptest
- name: fetching value of local file /home/sayani.bose@dryicelabs.com/playbook/roles/test/tasks/main.yml
  debug:
    msg: The details of /home/sayani.bose@dryicelabs.com/playbook/roles/test/tasks/main.yml--->{{lookup('file', '/home/sayani.bose@dryicelabs.com/playbook/roles/test/tasks/main.yml')}}

- name: fetching value of local file /home/sayani.bose@dryicelabs.com/playbook/roles/temp/templates/tempscript.sh.j2
  debug:
    msg: The details of /home/sayani.bose@dryicelabs.com/playbook/roles/temp/templates/tempscript.sh.j2-------{{lookup('file', '/home/sayani.bose@dryicelabs.com/playbook/roles/temp/templates/tempscript.sh.j2')}}

- name: adding inner.yml
  include_tasks: inner.yml
  loop:
    - 1
    - 2
    - 3
  loop_control:
    loop_var: outer_item

- name: printing the values which is greater than 5
  command: echo "{{ item }}"
  loop: [ 0, 2, 4, 6, 8, 10, 12, 14, 16 ]
  when: item > 5

- name: Creating a new file
  file:
    path: /tmp/sayani/dir1/a.txt
    state: touch
    mode: '0755'

- name: Writing the values which is greater than 5 in a file
  lineinfile:
    path: /tmp/sayani/dir1/a.txt
    line: "{{ item }}"
    insertbefore: EOF
  loop: [ 0, 2, 4, 6, 8, 10, 12, 14, 16 ]
  when: item > 5
- name: Creating a new file
  file:
    path: /tmp/sayani/dir1/a.txt
    state: touch
    mode: '0755'

- name: Writing the values which is greater than 5 in a file
  lineinfile:
    path: /tmp/sayani/dir1/a.txt
    line: "{{ item }}"
    insertbefore: EOF
  loop: [ 0, 2, 4, 6, 8, 10, 12, 14, 16 ]
  when: item > 5

- name: Creating s new file
  file:
    path: /tmp/sayani/dir1/b.txt
    state: touch
    mode: '0755'

- name: Storing file content in a variable
  set_fact:
    storevalue: "{{ lookup ( 'file', '/home/sayani.bose@dryicelabs.com/playbook/roles/test/tasks/main.yml') }}"

- name: Writing the one file's content into another file
  lineinfile:
    path: /tmp/sayani/dir1/b.txt
    line: "{{ storevalue }}"
    insertbefore: EOF

