---
# tasks file for looptest

- name: printing the values which is greater than 5
  command: echo "{{ item }}"
  loop: [ 0, 2, 4, 6, 8, 10, 12, 14, 16 ]
  when: item > 5

- name: Creating a new file
  file:
    path: /tmp/sayani/dir1/a.txt
    state: touch
    mode: '0755'

- name: Writing the values which is greater than 5 in a file
  lineinfile:
    path: /tmp/sayani/dir1/a.txt
    line: "{{ item }}"
    insertbefore: EOF
  loop: [ 0, 2, 4, 6, 8, 10, 12, 14, 16 ]
  when: item > 5
- name: Creating a new file
  file:
    path: /tmp/sayani/dir1/a.txt
    state: touch
    mode: '0755'

- name: Writing the values which is greater than 5 in a file
  lineinfile:
    path: /tmp/sayani/dir1/a.txt
    line: "{{ item }}"
    insertbefore: EOF
  loop: [ 0, 2, 4, 6, 8, 10, 12, 14, 16 ]
  when: item > 5





